name: clickhouse_connector
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CHVER:-latest}'
    environment:
      CLICKHOUSE_DB: bytewax
      CLICKHOUSE_USER: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
